apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  labels:
    app: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "50m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mywebapp2
  labels:
    app: mywebapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp2
  serviceName: "mywebapp2"
  template:
    metadata:
      labels:
        app: mywebapp2
    spec:
      containers:
      - name: mywebapp2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "50m"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mywebapp4
  labels:
    k8s-app: mywebapp4
spec:
  selector:
    matchLabels:
      name: mywebapp4
  template:
    metadata:
      labels:
        name: mywebapp4
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: mywebapp4
        image: nginx:1.14.2
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: "32Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Pod
metadata:
  name: mywebapp3
  labels:
    name: mywebapp3
spec:
  containers:
  - name: mywebapp3
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "32Mi"
        cpu: "50m"
    ports:
      - containerPort: 80